# flake8: NOQA
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from optuna.protobuf import session_pb2 as optuna_dot_protobuf_dot_session__pb2


class SessionStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.allocate_session = channel.unary_unary(
            '/optuna.protobuf.Session/allocate_session',
            request_serializer=optuna_dot_protobuf_dot_session__pb2.SessionAllocateRequest.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_session__pb2.SessionRef.FromString,
        )
        self.release_session = channel.unary_unary(
            '/optuna.protobuf.Session/release_session',
            request_serializer=optuna_dot_protobuf_dot_session__pb2.SessionRef.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.heartbeat_session = channel.unary_unary(
            '/optuna.protobuf.Session/heartbeat_session',
            request_serializer=optuna_dot_protobuf_dot_session__pb2.SessionRef.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class SessionServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def allocate_session(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def release_session(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def heartbeat_session(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'allocate_session': grpc.unary_unary_rpc_method_handler(
            servicer.allocate_session,
            request_deserializer=optuna_dot_protobuf_dot_session__pb2.SessionAllocateRequest.FromString,
            response_serializer=optuna_dot_protobuf_dot_session__pb2.SessionRef.SerializeToString,
        ),
        'release_session': grpc.unary_unary_rpc_method_handler(
            servicer.release_session,
            request_deserializer=optuna_dot_protobuf_dot_session__pb2.SessionRef.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'heartbeat_session': grpc.unary_unary_rpc_method_handler(
            servicer.heartbeat_session,
            request_deserializer=optuna_dot_protobuf_dot_session__pb2.SessionRef.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'optuna.protobuf.Session', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
