# flake8: NOQA
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from optuna.protobuf import structs_pb2 as optuna_dot_protobuf_dot_structs__pb2
from optuna.protobuf import study_pb2 as optuna_dot_protobuf_dot_study__pb2


class StudyStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.create_study = channel.unary_unary(
            '/optuna.protobuf.Study/create_study',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.CreateStudyRequest.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_study__pb2.StudyRef.FromString,
        )
        self.load_study = channel.unary_unary(
            '/optuna.protobuf.Study/load_study',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.LoadStudyRequest.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_study__pb2.StudyRef.FromString,
        )
        self.close_study = channel.unary_unary(
            '/optuna.protobuf.Study/close_study',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.StudyRef.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.trials = channel.unary_stream(
            '/optuna.protobuf.Study/trials',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.StudyRef.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_structs__pb2.FrozenTrial.FromString,
        )
        self.set_user_attr = channel.unary_unary(
            '/optuna.protobuf.Study/set_user_attr',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.SetUserAttrRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.study_summary = channel.unary_unary(
            '/optuna.protobuf.Study/study_summary',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.StudyRef.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_structs__pb2.StudySummary.FromString,
        )
        self.get_all_study_summaries = channel.unary_stream(
            '/optuna.protobuf.Study/get_all_study_summaries',
            request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_structs__pb2.StudySummary.FromString,
        )


class StudyServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def create_study(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def load_study(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def close_study(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def trials(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_user_attr(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def study_summary(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_study_summaries(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudyServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'create_study': grpc.unary_unary_rpc_method_handler(
            servicer.create_study,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.CreateStudyRequest.FromString,
            response_serializer=optuna_dot_protobuf_dot_study__pb2.StudyRef.SerializeToString,
        ),
        'load_study': grpc.unary_unary_rpc_method_handler(
            servicer.load_study,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.LoadStudyRequest.FromString,
            response_serializer=optuna_dot_protobuf_dot_study__pb2.StudyRef.SerializeToString,
        ),
        'close_study': grpc.unary_unary_rpc_method_handler(
            servicer.close_study,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.StudyRef.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'trials': grpc.unary_stream_rpc_method_handler(
            servicer.trials,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.StudyRef.FromString,
            response_serializer=optuna_dot_protobuf_dot_structs__pb2.FrozenTrial.SerializeToString,
        ),
        'set_user_attr': grpc.unary_unary_rpc_method_handler(
            servicer.set_user_attr,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.SetUserAttrRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'study_summary': grpc.unary_unary_rpc_method_handler(
            servicer.study_summary,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.StudyRef.FromString,
            response_serializer=optuna_dot_protobuf_dot_structs__pb2.StudySummary.SerializeToString,
        ),
        'get_all_study_summaries': grpc.unary_stream_rpc_method_handler(
            servicer.get_all_study_summaries,
            request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            response_serializer=optuna_dot_protobuf_dot_structs__pb2.StudySummary.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'optuna.protobuf.Study', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
