name: mac Integration Tests

on:
  push:
    branches:
      - main
  pull_request: {}
  schedule:
    - cron: '0 23 * * SUN-THU'

jobs:
  tests-integration:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest] # TODO: , windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Setup cache
      uses: actions/cache@v2
      env:
        cache-name: test-integration
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-3.7-${{ env.cache-name }}-${{ hashFiles('**/setup.py') }}-v1
        restore-keys: |
          ${{ runner.os }}-3.7-${{ env.cache-name }}-${{ hashFiles('**/setup.py') }}

    - name: Setup mac environment
      run: |
        brew install libomp
        brew install open-mpi

    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools

        # Install minimal dependencies and confirm that `import optuna` is successful.
        pip install --progress-bar off .
        python -c 'import optuna'
        optuna --version

        pip install --progress-bar off .[tests]
        pip install --progress-bar off .[integration] -f https://download.pytorch.org/whl/torch_stable.html

    - name: Tests
      run: |
        if [ ${{ matrix.python-version }} = 3.6 ]; then
          pytest tests/integration_tests \
            --ignore tests/integration_tests/test_botorch.py
        elif [ ${{ matrix.python-version }} = 3.8 ]; then
          pytest tests/integration_tests \
            --ignore tests/integration_tests/allennlp_tests/test_allennlp.py
        else
          # pytest cannot collect allennlp tests with allennlp==1.0.0.
          pytest -s tests/integration_tests
        fi

    - name: Tests MPI
      run: |
        mpirun -n 2 -- pytest tests/integration_tests/test_chainermn.py
      env:
        OMP_NUM_THREADS: 1
